### ISSUE TITLE
좋은 자료 감사합니다!!

### ISSUE THREAD

**Issue by V0tis** [rhostem/redux-saga-toaster-control#1]
바로 사용해볼게요 정말 고맙습니다 ㅎㅎ

**Comment by rhostem** [comment]
네 도움이 되었으면 좋겠습니다. 이거 올린지도 거의 2년이 다 되어가네요 😅

**Comment by V0tis** [comment]
헉ㅋㅋㅋ 2년이라니.. 변화가 엄청 왔을 것 같은데.. 😅
